System.config({
  defaultJSExtensions: true,
  transpiler: false,
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "*": "dist/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "resources/*.css": "resources/*.css"
  },
  bundles: {
    "stampweb-css-styles.js": [
      "resources/styles/bootstrap.css!github:systemjs/plugin-text@0.0.7.js",
      "resources/styles/styles.css!github:systemjs/plugin-text@0.0.7.js"
    ],
    "core-lib.js": [
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "github:systemjs/plugin-css@0.1.20.js",
      "github:systemjs/plugin-css@0.1.20/css.js",
      "github:systemjs/plugin-text@0.0.7.js",
      "github:systemjs/plugin-text@0.0.7/text.js",
      "npm:core-js@2.1.3.js",
      "npm:core-js@2.1.3/index.js",
      "npm:core-js@2.1.3/modules/_a-function.js",
      "npm:core-js@2.1.3/modules/_a-number-value.js",
      "npm:core-js@2.1.3/modules/_add-to-unscopables.js",
      "npm:core-js@2.1.3/modules/_an-instance.js",
      "npm:core-js@2.1.3/modules/_an-object.js",
      "npm:core-js@2.1.3/modules/_array-copy-within.js",
      "npm:core-js@2.1.3/modules/_array-fill.js",
      "npm:core-js@2.1.3/modules/_array-from-iterable.js",
      "npm:core-js@2.1.3/modules/_array-includes.js",
      "npm:core-js@2.1.3/modules/_array-methods.js",
      "npm:core-js@2.1.3/modules/_array-reduce.js",
      "npm:core-js@2.1.3/modules/_array-species-create.js",
      "npm:core-js@2.1.3/modules/_bind.js",
      "npm:core-js@2.1.3/modules/_classof.js",
      "npm:core-js@2.1.3/modules/_cof.js",
      "npm:core-js@2.1.3/modules/_collection-strong.js",
      "npm:core-js@2.1.3/modules/_collection-to-json.js",
      "npm:core-js@2.1.3/modules/_collection-weak.js",
      "npm:core-js@2.1.3/modules/_collection.js",
      "npm:core-js@2.1.3/modules/_core.js",
      "npm:core-js@2.1.3/modules/_ctx.js",
      "npm:core-js@2.1.3/modules/_defined.js",
      "npm:core-js@2.1.3/modules/_descriptors.js",
      "npm:core-js@2.1.3/modules/_dom-create.js",
      "npm:core-js@2.1.3/modules/_enum-bug-keys.js",
      "npm:core-js@2.1.3/modules/_enum-keys.js",
      "npm:core-js@2.1.3/modules/_export.js",
      "npm:core-js@2.1.3/modules/_fails-is-regexp.js",
      "npm:core-js@2.1.3/modules/_fails.js",
      "npm:core-js@2.1.3/modules/_fix-re-wks.js",
      "npm:core-js@2.1.3/modules/_flags.js",
      "npm:core-js@2.1.3/modules/_for-of.js",
      "npm:core-js@2.1.3/modules/_global.js",
      "npm:core-js@2.1.3/modules/_has.js",
      "npm:core-js@2.1.3/modules/_hide.js",
      "npm:core-js@2.1.3/modules/_html.js",
      "npm:core-js@2.1.3/modules/_ie8-dom-define.js",
      "npm:core-js@2.1.3/modules/_inherit-if-required.js",
      "npm:core-js@2.1.3/modules/_invoke.js",
      "npm:core-js@2.1.3/modules/_iobject.js",
      "npm:core-js@2.1.3/modules/_is-array-iter.js",
      "npm:core-js@2.1.3/modules/_is-array.js",
      "npm:core-js@2.1.3/modules/_is-integer.js",
      "npm:core-js@2.1.3/modules/_is-object.js",
      "npm:core-js@2.1.3/modules/_is-regexp.js",
      "npm:core-js@2.1.3/modules/_iter-call.js",
      "npm:core-js@2.1.3/modules/_iter-create.js",
      "npm:core-js@2.1.3/modules/_iter-define.js",
      "npm:core-js@2.1.3/modules/_iter-detect.js",
      "npm:core-js@2.1.3/modules/_iter-step.js",
      "npm:core-js@2.1.3/modules/_iterators.js",
      "npm:core-js@2.1.3/modules/_keyof.js",
      "npm:core-js@2.1.3/modules/_library.js",
      "npm:core-js@2.1.3/modules/_math-expm1.js",
      "npm:core-js@2.1.3/modules/_math-log1p.js",
      "npm:core-js@2.1.3/modules/_math-sign.js",
      "npm:core-js@2.1.3/modules/_meta.js",
      "npm:core-js@2.1.3/modules/_metadata.js",
      "npm:core-js@2.1.3/modules/_microtask.js",
      "npm:core-js@2.1.3/modules/_object-assign.js",
      "npm:core-js@2.1.3/modules/_object-create.js",
      "npm:core-js@2.1.3/modules/_object-define.js",
      "npm:core-js@2.1.3/modules/_object-dp.js",
      "npm:core-js@2.1.3/modules/_object-dps.js",
      "npm:core-js@2.1.3/modules/_object-gopd.js",
      "npm:core-js@2.1.3/modules/_object-gopn-ext.js",
      "npm:core-js@2.1.3/modules/_object-gopn.js",
      "npm:core-js@2.1.3/modules/_object-gops.js",
      "npm:core-js@2.1.3/modules/_object-gpo.js",
      "npm:core-js@2.1.3/modules/_object-keys-internal.js",
      "npm:core-js@2.1.3/modules/_object-keys.js",
      "npm:core-js@2.1.3/modules/_object-pie.js",
      "npm:core-js@2.1.3/modules/_object-sap.js",
      "npm:core-js@2.1.3/modules/_object-to-array.js",
      "npm:core-js@2.1.3/modules/_own-keys.js",
      "npm:core-js@2.1.3/modules/_parse-float.js",
      "npm:core-js@2.1.3/modules/_parse-int.js",
      "npm:core-js@2.1.3/modules/_partial.js",
      "npm:core-js@2.1.3/modules/_path.js",
      "npm:core-js@2.1.3/modules/_property-desc.js",
      "npm:core-js@2.1.3/modules/_redefine-all.js",
      "npm:core-js@2.1.3/modules/_redefine.js",
      "npm:core-js@2.1.3/modules/_replacer.js",
      "npm:core-js@2.1.3/modules/_same-value.js",
      "npm:core-js@2.1.3/modules/_set-proto.js",
      "npm:core-js@2.1.3/modules/_set-species.js",
      "npm:core-js@2.1.3/modules/_set-to-string-tag.js",
      "npm:core-js@2.1.3/modules/_shared-key.js",
      "npm:core-js@2.1.3/modules/_shared.js",
      "npm:core-js@2.1.3/modules/_species-constructor.js",
      "npm:core-js@2.1.3/modules/_strict-method.js",
      "npm:core-js@2.1.3/modules/_string-at.js",
      "npm:core-js@2.1.3/modules/_string-context.js",
      "npm:core-js@2.1.3/modules/_string-html.js",
      "npm:core-js@2.1.3/modules/_string-pad.js",
      "npm:core-js@2.1.3/modules/_string-repeat.js",
      "npm:core-js@2.1.3/modules/_string-trim.js",
      "npm:core-js@2.1.3/modules/_string-ws.js",
      "npm:core-js@2.1.3/modules/_task.js",
      "npm:core-js@2.1.3/modules/_to-index.js",
      "npm:core-js@2.1.3/modules/_to-integer.js",
      "npm:core-js@2.1.3/modules/_to-iobject.js",
      "npm:core-js@2.1.3/modules/_to-length.js",
      "npm:core-js@2.1.3/modules/_to-object.js",
      "npm:core-js@2.1.3/modules/_to-primitive.js",
      "npm:core-js@2.1.3/modules/_typed-array.js",
      "npm:core-js@2.1.3/modules/_typed-buffer.js",
      "npm:core-js@2.1.3/modules/_typed.js",
      "npm:core-js@2.1.3/modules/_uid.js",
      "npm:core-js@2.1.3/modules/_wks.js",
      "npm:core-js@2.1.3/modules/core.delay.js",
      "npm:core-js@2.1.3/modules/core.dict.js",
      "npm:core-js@2.1.3/modules/core.function.part.js",
      "npm:core-js@2.1.3/modules/core.get-iterator-method.js",
      "npm:core-js@2.1.3/modules/core.get-iterator.js",
      "npm:core-js@2.1.3/modules/core.is-iterable.js",
      "npm:core-js@2.1.3/modules/core.number.iterator.js",
      "npm:core-js@2.1.3/modules/core.object.classof.js",
      "npm:core-js@2.1.3/modules/core.object.define.js",
      "npm:core-js@2.1.3/modules/core.object.is-object.js",
      "npm:core-js@2.1.3/modules/core.object.make.js",
      "npm:core-js@2.1.3/modules/core.regexp.escape.js",
      "npm:core-js@2.1.3/modules/core.string.escape-html.js",
      "npm:core-js@2.1.3/modules/core.string.unescape-html.js",
      "npm:core-js@2.1.3/modules/es6.array.copy-within.js",
      "npm:core-js@2.1.3/modules/es6.array.every.js",
      "npm:core-js@2.1.3/modules/es6.array.fill.js",
      "npm:core-js@2.1.3/modules/es6.array.filter.js",
      "npm:core-js@2.1.3/modules/es6.array.find-index.js",
      "npm:core-js@2.1.3/modules/es6.array.find.js",
      "npm:core-js@2.1.3/modules/es6.array.for-each.js",
      "npm:core-js@2.1.3/modules/es6.array.from.js",
      "npm:core-js@2.1.3/modules/es6.array.index-of.js",
      "npm:core-js@2.1.3/modules/es6.array.is-array.js",
      "npm:core-js@2.1.3/modules/es6.array.iterator.js",
      "npm:core-js@2.1.3/modules/es6.array.join.js",
      "npm:core-js@2.1.3/modules/es6.array.last-index-of.js",
      "npm:core-js@2.1.3/modules/es6.array.map.js",
      "npm:core-js@2.1.3/modules/es6.array.of.js",
      "npm:core-js@2.1.3/modules/es6.array.reduce-right.js",
      "npm:core-js@2.1.3/modules/es6.array.reduce.js",
      "npm:core-js@2.1.3/modules/es6.array.slice.js",
      "npm:core-js@2.1.3/modules/es6.array.some.js",
      "npm:core-js@2.1.3/modules/es6.array.sort.js",
      "npm:core-js@2.1.3/modules/es6.array.species.js",
      "npm:core-js@2.1.3/modules/es6.date.now.js",
      "npm:core-js@2.1.3/modules/es6.date.to-iso-string.js",
      "npm:core-js@2.1.3/modules/es6.date.to-json.js",
      "npm:core-js@2.1.3/modules/es6.date.to-string.js",
      "npm:core-js@2.1.3/modules/es6.function.bind.js",
      "npm:core-js@2.1.3/modules/es6.function.has-instance.js",
      "npm:core-js@2.1.3/modules/es6.function.name.js",
      "npm:core-js@2.1.3/modules/es6.map.js",
      "npm:core-js@2.1.3/modules/es6.math.acosh.js",
      "npm:core-js@2.1.3/modules/es6.math.asinh.js",
      "npm:core-js@2.1.3/modules/es6.math.atanh.js",
      "npm:core-js@2.1.3/modules/es6.math.cbrt.js",
      "npm:core-js@2.1.3/modules/es6.math.clz32.js",
      "npm:core-js@2.1.3/modules/es6.math.cosh.js",
      "npm:core-js@2.1.3/modules/es6.math.expm1.js",
      "npm:core-js@2.1.3/modules/es6.math.fround.js",
      "npm:core-js@2.1.3/modules/es6.math.hypot.js",
      "npm:core-js@2.1.3/modules/es6.math.imul.js",
      "npm:core-js@2.1.3/modules/es6.math.log10.js",
      "npm:core-js@2.1.3/modules/es6.math.log1p.js",
      "npm:core-js@2.1.3/modules/es6.math.log2.js",
      "npm:core-js@2.1.3/modules/es6.math.sign.js",
      "npm:core-js@2.1.3/modules/es6.math.sinh.js",
      "npm:core-js@2.1.3/modules/es6.math.tanh.js",
      "npm:core-js@2.1.3/modules/es6.math.trunc.js",
      "npm:core-js@2.1.3/modules/es6.number.constructor.js",
      "npm:core-js@2.1.3/modules/es6.number.epsilon.js",
      "npm:core-js@2.1.3/modules/es6.number.is-finite.js",
      "npm:core-js@2.1.3/modules/es6.number.is-integer.js",
      "npm:core-js@2.1.3/modules/es6.number.is-nan.js",
      "npm:core-js@2.1.3/modules/es6.number.is-safe-integer.js",
      "npm:core-js@2.1.3/modules/es6.number.max-safe-integer.js",
      "npm:core-js@2.1.3/modules/es6.number.min-safe-integer.js",
      "npm:core-js@2.1.3/modules/es6.number.parse-float.js",
      "npm:core-js@2.1.3/modules/es6.number.parse-int.js",
      "npm:core-js@2.1.3/modules/es6.number.to-fixed.js",
      "npm:core-js@2.1.3/modules/es6.number.to-precision.js",
      "npm:core-js@2.1.3/modules/es6.object.assign.js",
      "npm:core-js@2.1.3/modules/es6.object.create.js",
      "npm:core-js@2.1.3/modules/es6.object.define-properties.js",
      "npm:core-js@2.1.3/modules/es6.object.define-property.js",
      "npm:core-js@2.1.3/modules/es6.object.freeze.js",
      "npm:core-js@2.1.3/modules/es6.object.get-own-property-descriptor.js",
      "npm:core-js@2.1.3/modules/es6.object.get-own-property-names.js",
      "npm:core-js@2.1.3/modules/es6.object.get-prototype-of.js",
      "npm:core-js@2.1.3/modules/es6.object.is-extensible.js",
      "npm:core-js@2.1.3/modules/es6.object.is-frozen.js",
      "npm:core-js@2.1.3/modules/es6.object.is-sealed.js",
      "npm:core-js@2.1.3/modules/es6.object.is.js",
      "npm:core-js@2.1.3/modules/es6.object.keys.js",
      "npm:core-js@2.1.3/modules/es6.object.prevent-extensions.js",
      "npm:core-js@2.1.3/modules/es6.object.seal.js",
      "npm:core-js@2.1.3/modules/es6.object.set-prototype-of.js",
      "npm:core-js@2.1.3/modules/es6.object.to-string.js",
      "npm:core-js@2.1.3/modules/es6.parse-float.js",
      "npm:core-js@2.1.3/modules/es6.parse-int.js",
      "npm:core-js@2.1.3/modules/es6.promise.js",
      "npm:core-js@2.1.3/modules/es6.reflect.apply.js",
      "npm:core-js@2.1.3/modules/es6.reflect.construct.js",
      "npm:core-js@2.1.3/modules/es6.reflect.define-property.js",
      "npm:core-js@2.1.3/modules/es6.reflect.delete-property.js",
      "npm:core-js@2.1.3/modules/es6.reflect.enumerate.js",
      "npm:core-js@2.1.3/modules/es6.reflect.get-own-property-descriptor.js",
      "npm:core-js@2.1.3/modules/es6.reflect.get-prototype-of.js",
      "npm:core-js@2.1.3/modules/es6.reflect.get.js",
      "npm:core-js@2.1.3/modules/es6.reflect.has.js",
      "npm:core-js@2.1.3/modules/es6.reflect.is-extensible.js",
      "npm:core-js@2.1.3/modules/es6.reflect.own-keys.js",
      "npm:core-js@2.1.3/modules/es6.reflect.prevent-extensions.js",
      "npm:core-js@2.1.3/modules/es6.reflect.set-prototype-of.js",
      "npm:core-js@2.1.3/modules/es6.reflect.set.js",
      "npm:core-js@2.1.3/modules/es6.regexp.constructor.js",
      "npm:core-js@2.1.3/modules/es6.regexp.flags.js",
      "npm:core-js@2.1.3/modules/es6.regexp.match.js",
      "npm:core-js@2.1.3/modules/es6.regexp.replace.js",
      "npm:core-js@2.1.3/modules/es6.regexp.search.js",
      "npm:core-js@2.1.3/modules/es6.regexp.split.js",
      "npm:core-js@2.1.3/modules/es6.regexp.to-string.js",
      "npm:core-js@2.1.3/modules/es6.set.js",
      "npm:core-js@2.1.3/modules/es6.string.anchor.js",
      "npm:core-js@2.1.3/modules/es6.string.big.js",
      "npm:core-js@2.1.3/modules/es6.string.blink.js",
      "npm:core-js@2.1.3/modules/es6.string.bold.js",
      "npm:core-js@2.1.3/modules/es6.string.code-point-at.js",
      "npm:core-js@2.1.3/modules/es6.string.ends-with.js",
      "npm:core-js@2.1.3/modules/es6.string.fixed.js",
      "npm:core-js@2.1.3/modules/es6.string.fontcolor.js",
      "npm:core-js@2.1.3/modules/es6.string.fontsize.js",
      "npm:core-js@2.1.3/modules/es6.string.from-code-point.js",
      "npm:core-js@2.1.3/modules/es6.string.includes.js",
      "npm:core-js@2.1.3/modules/es6.string.italics.js",
      "npm:core-js@2.1.3/modules/es6.string.iterator.js",
      "npm:core-js@2.1.3/modules/es6.string.link.js",
      "npm:core-js@2.1.3/modules/es6.string.raw.js",
      "npm:core-js@2.1.3/modules/es6.string.repeat.js",
      "npm:core-js@2.1.3/modules/es6.string.small.js",
      "npm:core-js@2.1.3/modules/es6.string.starts-with.js",
      "npm:core-js@2.1.3/modules/es6.string.strike.js",
      "npm:core-js@2.1.3/modules/es6.string.sub.js",
      "npm:core-js@2.1.3/modules/es6.string.sup.js",
      "npm:core-js@2.1.3/modules/es6.string.trim.js",
      "npm:core-js@2.1.3/modules/es6.symbol.js",
      "npm:core-js@2.1.3/modules/es6.typed.array-buffer.js",
      "npm:core-js@2.1.3/modules/es6.typed.data-view.js",
      "npm:core-js@2.1.3/modules/es6.typed.float32-array.js",
      "npm:core-js@2.1.3/modules/es6.typed.float64-array.js",
      "npm:core-js@2.1.3/modules/es6.typed.int16-array.js",
      "npm:core-js@2.1.3/modules/es6.typed.int32-array.js",
      "npm:core-js@2.1.3/modules/es6.typed.int8-array.js",
      "npm:core-js@2.1.3/modules/es6.typed.uint16-array.js",
      "npm:core-js@2.1.3/modules/es6.typed.uint32-array.js",
      "npm:core-js@2.1.3/modules/es6.typed.uint8-array.js",
      "npm:core-js@2.1.3/modules/es6.typed.uint8-clamped-array.js",
      "npm:core-js@2.1.3/modules/es6.weak-map.js",
      "npm:core-js@2.1.3/modules/es6.weak-set.js",
      "npm:core-js@2.1.3/modules/es7.array.includes.js",
      "npm:core-js@2.1.3/modules/es7.error.is-error.js",
      "npm:core-js@2.1.3/modules/es7.map.to-json.js",
      "npm:core-js@2.1.3/modules/es7.math.iaddh.js",
      "npm:core-js@2.1.3/modules/es7.math.imulh.js",
      "npm:core-js@2.1.3/modules/es7.math.isubh.js",
      "npm:core-js@2.1.3/modules/es7.math.umulh.js",
      "npm:core-js@2.1.3/modules/es7.object.entries.js",
      "npm:core-js@2.1.3/modules/es7.object.get-own-property-descriptors.js",
      "npm:core-js@2.1.3/modules/es7.object.values.js",
      "npm:core-js@2.1.3/modules/es7.reflect.define-metadata.js",
      "npm:core-js@2.1.3/modules/es7.reflect.delete-metadata.js",
      "npm:core-js@2.1.3/modules/es7.reflect.get-metadata-keys.js",
      "npm:core-js@2.1.3/modules/es7.reflect.get-metadata.js",
      "npm:core-js@2.1.3/modules/es7.reflect.get-own-metadata-keys.js",
      "npm:core-js@2.1.3/modules/es7.reflect.get-own-metadata.js",
      "npm:core-js@2.1.3/modules/es7.reflect.has-metadata.js",
      "npm:core-js@2.1.3/modules/es7.reflect.has-own-metadata.js",
      "npm:core-js@2.1.3/modules/es7.reflect.metadata.js",
      "npm:core-js@2.1.3/modules/es7.set.to-json.js",
      "npm:core-js@2.1.3/modules/es7.string.at.js",
      "npm:core-js@2.1.3/modules/es7.string.pad-end.js",
      "npm:core-js@2.1.3/modules/es7.string.pad-start.js",
      "npm:core-js@2.1.3/modules/es7.string.trim-left.js",
      "npm:core-js@2.1.3/modules/es7.string.trim-right.js",
      "npm:core-js@2.1.3/modules/es7.system.global.js",
      "npm:core-js@2.1.3/modules/web.dom.iterable.js",
      "npm:core-js@2.1.3/modules/web.immediate.js",
      "npm:core-js@2.1.3/modules/web.timers.js",
      "npm:core-js@2.1.3/shim.js",
      "npm:process@0.11.2.js",
      "npm:process@0.11.2/browser.js"
    ],
    "core-framework.js": [
      "npm:aurelia-animator-css@1.0.0-beta.1.2.0.js",
      "npm:aurelia-animator-css@1.0.0-beta.1.2.0/aurelia-animator-css.js",
      "npm:aurelia-binding@1.0.0-beta.1.3.0.js",
      "npm:aurelia-binding@1.0.0-beta.1.3.0/aurelia-binding.js",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.2.0.js",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.2.0/aurelia-bootstrapper.js",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0.js",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0/aurelia-dependency-injection.js",
      "npm:aurelia-dialog@0.5.10.js",
      "npm:aurelia-dialog@0.5.10/aurelia-dialog.js",
      "npm:aurelia-dialog@0.5.10/dialog-configuration.js",
      "npm:aurelia-dialog@0.5.10/dialog-controller.js",
      "npm:aurelia-dialog@0.5.10/dialog-options.js",
      "npm:aurelia-dialog@0.5.10/dialog-service.js",
      "npm:aurelia-dialog@0.5.10/dialog.css!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-dialog@0.5.10/lifecycle.js",
      "npm:aurelia-dialog@0.5.10/renderers/dialog-renderer.js",
      "npm:aurelia-dialog@0.5.10/renderers/renderer.js",
      "npm:aurelia-dialog@0.5.10/resources/ai-dialog-body.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-dialog@0.5.10/resources/ai-dialog-body.js",
      "npm:aurelia-dialog@0.5.10/resources/ai-dialog-footer.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-dialog@0.5.10/resources/ai-dialog-footer.js",
      "npm:aurelia-dialog@0.5.10/resources/ai-dialog-header.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-dialog@0.5.10/resources/ai-dialog-header.js",
      "npm:aurelia-dialog@0.5.10/resources/ai-dialog.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-dialog@0.5.10/resources/ai-dialog.js",
      "npm:aurelia-dialog@0.5.10/resources/attach-focus.js",
      "npm:aurelia-event-aggregator@1.0.0-beta.1.2.0.js",
      "npm:aurelia-event-aggregator@1.0.0-beta.1.2.0/aurelia-event-aggregator.js",
      "npm:aurelia-framework@1.0.0-beta.1.2.0.js",
      "npm:aurelia-framework@1.0.0-beta.1.2.0/aurelia-framework.js",
      "npm:aurelia-history-browser@1.0.0-beta.1.2.0.js",
      "npm:aurelia-history-browser@1.0.0-beta.1.2.0/aurelia-history-browser.js",
      "npm:aurelia-history@1.0.0-beta.1.2.0.js",
      "npm:aurelia-history@1.0.0-beta.1.2.0/aurelia-history.js",
      "npm:aurelia-html-import-template-loader@1.0.0-beta.1.2.0.js",
      "npm:aurelia-html-import-template-loader@1.0.0-beta.1.2.0/aurelia-html-import-template-loader.js",
      "npm:aurelia-http-client@1.0.0-beta.1.2.0.js",
      "npm:aurelia-http-client@1.0.0-beta.1.2.0/aurelia-http-client.js",
      "npm:aurelia-i18n@0.5.0.js",
      "npm:aurelia-i18n@0.5.0/aurelia-i18n.js",
      "npm:aurelia-i18n@0.5.0/base-i18n.js",
      "npm:aurelia-i18n@0.5.0/defaultTranslations/relative.time.js",
      "npm:aurelia-i18n@0.5.0/df.js",
      "npm:aurelia-i18n@0.5.0/i18n.js",
      "npm:aurelia-i18n@0.5.0/nf.js",
      "npm:aurelia-i18n@0.5.0/relativeTime.js",
      "npm:aurelia-i18n@0.5.0/rt.js",
      "npm:aurelia-i18n@0.5.0/t.js",
      "npm:aurelia-i18n@0.5.0/utils.js",
      "npm:aurelia-loader-default@1.0.0-beta.1.2.0.js",
      "npm:aurelia-loader-default@1.0.0-beta.1.2.0/aurelia-loader-default.js",
      "npm:aurelia-loader@1.0.0-beta.1.2.0.js",
      "npm:aurelia-loader@1.0.0-beta.1.2.0/aurelia-loader.js",
      "npm:aurelia-logging-console@1.0.0-beta.1.2.0.js",
      "npm:aurelia-logging-console@1.0.0-beta.1.2.0/aurelia-logging-console.js",
      "npm:aurelia-logging@1.0.0-beta.1.2.0.js",
      "npm:aurelia-logging@1.0.0-beta.1.2.0/aurelia-logging.js",
      "npm:aurelia-metadata@1.0.0-beta.1.2.0.js",
      "npm:aurelia-metadata@1.0.0-beta.1.2.0/aurelia-metadata.js",
      "npm:aurelia-pal-browser@1.0.0-beta.1.2.0.js",
      "npm:aurelia-pal-browser@1.0.0-beta.1.2.0/aurelia-pal-browser.js",
      "npm:aurelia-pal@1.0.0-beta.1.2.0.js",
      "npm:aurelia-pal@1.0.0-beta.1.2.0/aurelia-pal.js",
      "npm:aurelia-path@1.0.0-beta.1.2.0.js",
      "npm:aurelia-path@1.0.0-beta.1.2.0/aurelia-path.js",
      "npm:aurelia-polyfills@1.0.0-beta.1.1.0.js",
      "npm:aurelia-polyfills@1.0.0-beta.1.1.0/aurelia-polyfills.js",
      "npm:aurelia-route-recognizer@1.0.0-beta.1.2.0.js",
      "npm:aurelia-route-recognizer@1.0.0-beta.1.2.0/aurelia-route-recognizer.js",
      "npm:aurelia-router@1.0.0-beta.1.2.0.js",
      "npm:aurelia-router@1.0.0-beta.1.2.0/aurelia-router.js",
      "npm:aurelia-task-queue@1.0.0-beta.1.2.0.js",
      "npm:aurelia-task-queue@1.0.0-beta.1.2.0/aurelia-task-queue.js",
      "npm:aurelia-templating-binding@1.0.0-beta.1.2.0.js",
      "npm:aurelia-templating-binding@1.0.0-beta.1.2.0/aurelia-templating-binding.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/abstract-repeater.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/analyze-view-factory.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/array-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/aurelia-templating-resources.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/binding-mode-behaviors.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/binding-signaler.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/compile-spy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/compose.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/css-resource.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/debounce-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/dynamic-element.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/focus.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/hide.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/html-sanitizer.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/if.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/map-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/null-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/number-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/repeat-strategy-locator.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/repeat-utilities.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/repeat.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/replaceable.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/sanitize-html.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/set-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/show.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/signal-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/throttle-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/update-trigger-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/view-spy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.0/with.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.0.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.0/aurelia-templating-router.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.0/route-href.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.0/route-loader.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.0/router-view.js",
      "npm:aurelia-templating@1.0.0-beta.1.2.0.js",
      "npm:aurelia-templating@1.0.0-beta.1.2.0/aurelia-templating.js",
      "npm:aurelia-validation@0.6.6.js",
      "npm:aurelia-validation@0.6.6/debouncer.js",
      "npm:aurelia-validation@0.6.6/decorators.js",
      "npm:aurelia-validation@0.6.6/index.js",
      "npm:aurelia-validation@0.6.6/path-observer.js",
      "npm:aurelia-validation@0.6.6/strategies/twbootstrap-view-strategy.js",
      "npm:aurelia-validation@0.6.6/utilities.js",
      "npm:aurelia-validation@0.6.6/validate-custom-attribute.js",
      "npm:aurelia-validation@0.6.6/validation-config.js",
      "npm:aurelia-validation@0.6.6/validation-group-builder.js",
      "npm:aurelia-validation@0.6.6/validation-group.js",
      "npm:aurelia-validation@0.6.6/validation-locale.js",
      "npm:aurelia-validation@0.6.6/validation-property.js",
      "npm:aurelia-validation@0.6.6/validation-result.js",
      "npm:aurelia-validation@0.6.6/validation-rules-collection.js",
      "npm:aurelia-validation@0.6.6/validation-rules.js",
      "npm:aurelia-validation@0.6.6/validation-view-strategy.js",
      "npm:aurelia-validation@0.6.6/validation.js",
      "npm:i18next-xhr-backend@0.5.3.js",
      "npm:i18next-xhr-backend@0.5.3/dist/commonjs/index.js",
      "npm:i18next-xhr-backend@0.5.3/dist/commonjs/utils.js",
      "npm:i18next-xhr-backend@0.5.3/index.js",
      "npm:i18next@2.5.1.js",
      "npm:i18next@2.5.1/dist/commonjs/BackendConnector.js",
      "npm:i18next@2.5.1/dist/commonjs/CacheConnector.js",
      "npm:i18next@2.5.1/dist/commonjs/EventEmitter.js",
      "npm:i18next@2.5.1/dist/commonjs/Interpolator.js",
      "npm:i18next@2.5.1/dist/commonjs/LanguageUtils.js",
      "npm:i18next@2.5.1/dist/commonjs/PluralResolver.js",
      "npm:i18next@2.5.1/dist/commonjs/ResourceStore.js",
      "npm:i18next@2.5.1/dist/commonjs/Translator.js",
      "npm:i18next@2.5.1/dist/commonjs/compatibility/v1.js",
      "npm:i18next@2.5.1/dist/commonjs/defaults.js",
      "npm:i18next@2.5.1/dist/commonjs/i18next.js",
      "npm:i18next@2.5.1/dist/commonjs/index.js",
      "npm:i18next@2.5.1/dist/commonjs/logger.js",
      "npm:i18next@2.5.1/dist/commonjs/postProcessor.js",
      "npm:i18next@2.5.1/dist/commonjs/utils.js",
      "npm:i18next@2.5.1/index.js"
    ],
    "datepicker.js": [
      "npm:bootstrap-datepicker@1.6.0.js",
      "npm:bootstrap-datepicker@1.6.0/dist/css/bootstrap-datepicker3.css!github:systemjs/plugin-text@0.0.7.js",
      "npm:bootstrap-datepicker@1.6.0/dist/js/bootstrap-datepicker.js",
      "resources/styles/widgets/date-picker/date-picker.css!github:systemjs/plugin-text@0.0.7.js",
      "widgets/date-picker/date-picker.html!github:systemjs/plugin-text@0.0.7.js",
      "widgets/date-picker/date-picker.js"
    ],
    "core-ui.js": [
      "github:moment/moment@2.10.3.js",
      "github:moment/moment@2.10.3/moment.js",
      "github:rstacruz/nprogress@0.1.6.js",
      "github:rstacruz/nprogress@0.1.6/nprogress.css!github:systemjs/plugin-css@0.1.20.js",
      "github:rstacruz/nprogress@0.1.6/nprogress.js",
      "github:twbs/bootstrap@3.3.6.js",
      "github:twbs/bootstrap@3.3.6/js/bootstrap.js",
      "npm:bootbox@4.4.0.js",
      "npm:bootbox@4.4.0/bootbox.js",
      "npm:jquery@2.2.1.js",
      "npm:jquery@2.2.1/dist/jquery.js",
      "npm:lodash@3.10.1.js",
      "npm:lodash@3.10.1/index.js"
    ],
    "stampweb-common.js": [
      "components/editor-dialog.html!github:systemjs/plugin-text@0.0.7.js",
      "components/editor-dialog.js",
      "components/loading-indicator.js",
      "components/nav/nav-bar.html!github:systemjs/plugin-text@0.0.7.js",
      "components/nav/nav-bar.js",
      "events/event-managed.js",
      "global-resources/default-value.js",
      "global-resources/index.js",
      "npm:odata-filter-parser@0.2.8.js",
      "npm:odata-filter-parser@0.2.8/dist/odata-parser.js",
      "npm:odata-filter-parser@0.2.8/index.js",
      "resources/styles/components/loading-indicator.css!github:systemjs/plugin-text@0.0.7.js",
      "resources/styles/components/nav/nav-bar.css!github:systemjs/plugin-text@0.0.7.js",
      "services/albums.js",
      "services/base-service.js",
      "services/catalogueNumbers.js",
      "services/catalogues.js",
      "services/countries.js",
      "services/entity-managed.js",
      "services/preferences.js",
      "services/sellers.js",
      "services/session-context.js",
      "services/stampCollections.js",
      "services/stamps.js",
      "util/common-models.js",
      "util/find-target.js",
      "util/location-helper.js",
      "util/object-utilities.js",
      "value-converters/as-currency-formatted.js",
      "value-converters/as-currency.js",
      "value-converters/as-enum.js",
      "value-converters/as-number.js",
      "value-converters/as-percentage.js",
      "value-converters/bitwise-to-array.js",
      "value-converters/by-name.js",
      "value-converters/date-formatter.js",
      "value-converters/empty-text.js",
      "value-converters/filter-by-name.js",
      "value-converters/rate-filter.js",
      "value-converters/stamp-count.js",
      "value-converters/zero-based.js"
    ],
    "stampweb-settings.js": [
      "resources/styles/views/preferences/user-settings.css!github:systemjs/plugin-text@0.0.7.js",
      "views/preferences/user-settings.html!github:systemjs/plugin-text@0.0.7.js",
      "views/preferences/user-settings.js"
    ],
    "stampweb-manage.js": [
      "resources/styles/views/manage/manage.css!github:systemjs/plugin-text@0.0.7.js",
      "views/albums/album-editor.html!github:systemjs/plugin-text@0.0.7.js",
      "views/albums/album-editor.js",
      "views/catalogues/catalogue-editor.html!github:systemjs/plugin-text@0.0.7.js",
      "views/catalogues/catalogue-editor.js",
      "views/countries/country-editor.html!github:systemjs/plugin-text@0.0.7.js",
      "views/countries/country-editor.js",
      "views/manage/list.html!github:systemjs/plugin-text@0.0.7.js",
      "views/manage/list.js",
      "views/manage/manage-list.html!github:systemjs/plugin-text@0.0.7.js",
      "views/manage/manage-list.js",
      "views/sellers/seller-editor.html!github:systemjs/plugin-text@0.0.7.js",
      "views/sellers/seller-editor.js",
      "views/stamp-collections/stamp-collection-editor.html!github:systemjs/plugin-text@0.0.7.js",
      "views/stamp-collections/stamp-collection-editor.js"
    ],
    "stampweb-widgets.js": [
      "github:blueimp/JavaScript-Load-Image@1.14.0.js",
      "github:blueimp/JavaScript-Load-Image@1.14.0/js/load-image.js",
      "github:select2/select2@4.0.0.js",
      "github:select2/select2@4.0.0/css/select2.css!github:systemjs/plugin-css@0.1.20.js",
      "github:select2/select2@4.0.0/css/select2.css!github:systemjs/plugin-text@0.0.7.js",
      "github:select2/select2@4.0.0/js/select2.js",
      "resources/styles/widgets/collapse-panel/collapse-panel.css!github:systemjs/plugin-text@0.0.7.js",
      "resources/styles/widgets/image-preview/image-preview.css!github:systemjs/plugin-text@0.0.7.js",
      "resources/styles/widgets/paging/paging-toolbar.css!github:systemjs/plugin-text@0.0.7.js",
      "resources/styles/widgets/select-picker/select-picker.css!github:systemjs/plugin-text@0.0.7.js",
      "widgets/collapse-panel/collapse-panel.html!github:systemjs/plugin-text@0.0.7.js",
      "widgets/collapse-panel/collapse-panel.js",
      "widgets/image-preview/image-preview.html!github:systemjs/plugin-text@0.0.7.js",
      "widgets/image-preview/image-preview.js",
      "widgets/paging/paging-toolbar.html!github:systemjs/plugin-text@0.0.7.js",
      "widgets/paging/paging-toolbar.js",
      "widgets/select-picker/select-picker.html!github:systemjs/plugin-text@0.0.7.js",
      "widgets/select-picker/select-picker.js"
    ],
    "stampweb-list.js": [
      "components/catalogue-numbers/cn-details.html!github:systemjs/plugin-text@0.0.7.js",
      "components/catalogue-numbers/cn-details.js",
      "components/catalogue-numbers/cn-references.html!github:systemjs/plugin-text@0.0.7.js",
      "components/catalogue-numbers/cn-references.js",
      "components/ownerships/ownership-cert.html!github:systemjs/plugin-text@0.0.7.js",
      "components/ownerships/ownership-cert.js",
      "components/ownerships/ownership-editor.html!github:systemjs/plugin-text@0.0.7.js",
      "components/ownerships/ownership-editor.js",
      "components/ownerships/ownership-notes.html!github:systemjs/plugin-text@0.0.7.js",
      "components/ownerships/ownership-notes.js",
      "components/search/search-form.html!github:systemjs/plugin-text@0.0.7.js",
      "components/search/search-form.js",
      "components/stamp-card.html!github:systemjs/plugin-text@0.0.7.js",
      "components/stamp-card.js",
      "components/stamp-grid.html!github:systemjs/plugin-text@0.0.7.js",
      "components/stamp-grid.js",
      "components/stamps/stamp-details.html!github:systemjs/plugin-text@0.0.7.js",
      "components/stamps/stamp-details.js",
      "components/stamps/stamp-editor.html!github:systemjs/plugin-text@0.0.7.js",
      "components/stamps/stamp-editor.js",
      "components/stamps/stamp-table.html!github:systemjs/plugin-text@0.0.7.js",
      "components/stamps/stamp-table.js",
      "resources/styles/components/catalogue-numbers/cn-details.css!github:systemjs/plugin-text@0.0.7.js",
      "resources/styles/components/catalogue-numbers/cn-references.css!github:systemjs/plugin-text@0.0.7.js",
      "resources/styles/components/ownerships/ownership-cert.css!github:systemjs/plugin-text@0.0.7.js",
      "resources/styles/components/ownerships/ownership-editor.css!github:systemjs/plugin-text@0.0.7.js",
      "resources/styles/components/ownerships/ownership-notes.css!github:systemjs/plugin-text@0.0.7.js",
      "resources/styles/components/search/search-form.css!github:systemjs/plugin-text@0.0.7.js",
      "resources/styles/components/stamp-card.css!github:systemjs/plugin-text@0.0.7.js",
      "resources/styles/components/stamp-grid.css!github:systemjs/plugin-text@0.0.7.js",
      "resources/styles/components/stamps/stamp-editor.css!github:systemjs/plugin-text@0.0.7.js",
      "resources/styles/components/stamps/stamp-table.css!github:systemjs/plugin-text@0.0.7.js",
      "resources/styles/views/stamps/purchase-form.css!github:systemjs/plugin-text@0.0.7.js",
      "resources/styles/views/stamps/stamp-list.css!github:systemjs/plugin-text@0.0.7.js",
      "views/stamps/purchase-form.html!github:systemjs/plugin-text@0.0.7.js",
      "views/stamps/purchase-form.js",
      "views/stamps/stamp-list.html!github:systemjs/plugin-text@0.0.7.js",
      "views/stamps/stamp-list.js"
    ]
  },

  map: {
    "aurelia-animator-css": "npm:aurelia-animator-css@1.0.0-beta.1.2.0",
    "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.0",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.1.2.0",
    "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0",
    "aurelia-dialog": "npm:aurelia-dialog@0.5.10",
    "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.2.0",
    "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.2.0",
    "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.2.0",
    "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.2.0",
    "aurelia-html-import-template-loader": "npm:aurelia-html-import-template-loader@1.0.0-beta.1.2.0",
    "aurelia-http-client": "npm:aurelia-http-client@1.0.0-beta.1.2.0",
    "aurelia-i18n": "npm:aurelia-i18n@0.5.0",
    "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
    "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.2.0",
    "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
    "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1.2.0",
    "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
    "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0",
    "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.1.2.0",
    "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.0",
    "aurelia-polyfills": "npm:aurelia-polyfills@1.0.0-beta.1.1.0",
    "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.0.0-beta.1.2.0",
    "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.0",
    "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.0",
    "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.0",
    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.2.0",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.2.0",
    "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.2.0",
    "aurelia-validation": "npm:aurelia-validation@0.6.6",
    "babel": "npm:babel-core@5.8.38",
    "babel-runtime": "npm:babel-runtime@5.8.38",
    "blueimp/JavaScript-Load-Image": "github:blueimp/JavaScript-Load-Image@1.14.0",
    "bootbox": "npm:bootbox@4.4.0",
    "bootstrap": "github:twbs/bootstrap@3.3.6",
    "bootstrap-datepicker": "npm:bootstrap-datepicker@1.6.0",
    "clean-css": "npm:clean-css@3.4.10",
    "core-js": "npm:core-js@2.1.3",
    "core-ui": "npm:core-ui@0.1.3",
    "css": "github:systemjs/plugin-css@0.1.20",
    "i18next-xhr-backend": "npm:i18next-xhr-backend@0.5.3",
    "jquery": "npm:jquery@2.2.1",
    "less": "github:aaike/jspm-less-plugin@0.0.5",
    "lodash": "npm:lodash@3.10.1",
    "moment": "github:moment/moment@2.10.3",
    "nprogress": "github:rstacruz/nprogress@0.1.6",
    "odata-filter-parser": "npm:odata-filter-parser@0.2.8",
    "select2/select2": "github:select2/select2@4.0.0",
    "systemjs": "npm:systemjs@0.19.26",
    "text": "github:systemjs/plugin-text@0.0.7",
    "webcomponents-lite": "npm:webcomponents-lite@0.6.0",
    "github:aaike/jspm-less-plugin@0.0.5": {
      "less.js": "github:distros/less@2.4.0"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-https@0.1.0": {
      "https-browserify": "npm:https-browserify@0.0.0"
    },
    "github:jspm/nodelibs-os@0.1.0": {
      "os-browserify": "npm:os-browserify@0.1.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:rstacruz/nprogress@0.1.6": {
      "css": "github:systemjs/plugin-css@0.1.20"
    },
    "github:select2/select2@4.0.0": {
      "jquery": "npm:jquery@2.2.1"
    },
    "github:twbs/bootstrap@3.3.6": {
      "jquery": "npm:jquery@2.2.1"
    },
    "npm:amdefine@1.0.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "module": "github:jspm/nodelibs-module@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:aurelia-animator-css@1.0.0-beta.1.2.0": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-binding@1.0.0-beta.1.3.0": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-bootstrapper@1.0.0-beta.1.2.0": {
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.2.0",
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.2.0",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.2.0",
      "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.2.0",
      "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.2.0",
      "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.1.2.0",
      "aurelia-polyfills": "npm:aurelia-polyfills@1.0.0-beta.1.1.0",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.0",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.2.0",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.2.0",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-dialog@0.5.10": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-event-aggregator@1.0.0-beta.1.2.0": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-framework@1.0.0-beta.1.2.0": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-history-browser@1.0.0-beta.1.2.0": {
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-html-import-template-loader@1.0.0-beta.1.2.0": {
      "webcomponentsjs": "npm:webcomponents-lite@0.6.0"
    },
    "npm:aurelia-http-client@1.0.0-beta.1.2.0": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-i18n@0.5.0": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.2.0",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.0",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.2.0",
      "i18next": "npm:i18next@2.5.1",
      "intl": "npm:intl@1.1.0"
    },
    "npm:aurelia-loader-default@1.0.0-beta.1.2.0": {
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-loader@1.0.0-beta.1.2.0": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-logging-console@1.0.0-beta.1.2.0": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-metadata@1.0.0-beta.1.2.0": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-pal-browser@1.0.0-beta.1.2.0": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-polyfills@1.0.0-beta.1.1.0": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-route-recognizer@1.0.0-beta.1.2.0": {
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-router@1.0.0-beta.1.2.0": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.2.0",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.0",
      "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-task-queue@1.0.0-beta.1.2.0": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-templating-binding@1.0.0-beta.1.2.0": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-templating-resources@1.0.0-beta.1.2.0": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-templating-router@1.0.0-beta.1.2.0": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.0",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-templating@1.0.0-beta.1.2.0": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.0",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-validation@0.6.6": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.0"
    },
    "npm:bootbox@4.4.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:bootstrap-datepicker@1.6.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "jquery": "npm:jquery@2.2.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.1"
    },
    "npm:clean-css@3.4.10": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "commander": "npm:commander@2.8.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "https": "github:jspm/nodelibs-https@0.1.0",
      "os": "github:jspm/nodelibs-os@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "source-map": "npm:source-map@0.4.4",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:commander@2.8.1": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "graceful-readlink": "npm:graceful-readlink@1.0.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:core-js@2.1.3": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.1"
    },
    "npm:core-ui@0.1.3": {
      "object-assign": "npm:object-assign@4.0.1"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:graceful-readlink@1.0.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2"
    },
    "npm:https-browserify@0.0.0": {
      "http": "github:jspm/nodelibs-http@1.7.1"
    },
    "npm:i18next@2.5.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:intl@1.1.0": {
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.1"
    },
    "npm:isarray@1.0.0": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.1"
    },
    "npm:lodash@3.10.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:os-browserify@0.1.2": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.14": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:source-map@0.4.4": {
      "amdefine": "npm:amdefine@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.14"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:systemjs@0.19.26": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.1",
      "when": "npm:when@3.7.7"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:webcomponents-lite@0.6.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:when@3.7.7": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
