export var EventNames = {
    calculateImagePath: 'calculate-image-path',
    changeEditMode: 'change-edit-mode',
    checkExists: 'check-exists',
    conflictExists: 'conflict-exists',
    convert: 'convert',
    close: "close-dialog",
    actionError: "action-error",
    keywordSearch: "keywordSearch",
    search: "search",
    showImage: "showImage",
    save: "save",
    edit: 'edit',

    create: 'create',
    manageEntity: "manage-entity",
    entityDelete: "entity-delete",
    selectEntity: "select-entity",
    entityFilter: "entity-filter",
    loadingStarted: "loading-started",
    loadingFinished: "loading-finished",
    preferenceChanged: "preference-changed",
    stampCreate: 'stamp-create',
    stampEdit: 'stamp-edit',
    stampEditorCancel: 'stamp-edit-cancel',
    stampRemove: 'stamp-remove',
    stampSaved: 'stamp-saved'
};
